from typing import Dict, Any

# Level 280 Localization Matrix
# Includes support for dynamic environmental variables and crop-stage awareness
TRANSLATIONS = {
    "en": {
        "welcome": "Welcome to AquaSense! Your User ID is {id}.",
        "registered": "User registered successfully.",
        "NO_DATA": "No sensor data received yet. Please check if your device is powered on.",
        
        # AI Reasoning Codes (Scientific & Explainable)
        "RAIN_FORECAST": "Rain is expected soon ({rainfall_mm}mm). Irrigation postponed to save water and prevent nutrient leaching.",
        "MOISTURE_ADEQUATE": "Soil moisture is healthy for the current stage. No irrigation needed.",
        "CRITICAL_MOISTURE": "Soil is critically dry! Immediate irrigation required to prevent wilting and crop stress.",
        "HEAT_STRESS": "High heat detected ({temp}°C). Light irrigation recommended to maintain plant turgor and cool the canopy.",
        "WAIT_AND_WATCH": "Soil-water balance is optimal. Conditions are being monitored.",
        "SENSOR_LOW_BATTERY": "Warning: Sensor battery is critically low. Accuracy may be compromised."
    },
    "hi": {
        "welcome": "AquaSense में आपका स्वागत है! आपकी यूजर आईडी {id} है।",
        "registered": "उपयोगकर्ता सफलतापूर्वक पंजीकृत।",
        "NO_DATA": "अभी तक कोई सेंसर डेटा प्राप्त नहीं हुआ। कृपया जांचें कि क्या आपका डिवाइस चालू है।",
        
        # AI Reasoning Codes (Hindi Localization)
        "RAIN_FORECAST": "जल्द ही बारिश ({rainfall_mm}mm) होने की संभावना है। पानी बचाने और उर्वरकों को बहने से रोकने के लिए सिंचाई स्थगित कर दी गई है।",
        "MOISTURE_ADEQUATE": "मिट्टी की नमी वर्तमान अवस्था के लिए पर्याप्त है। सिंचाई की आवश्यकता नहीं है।",
        "CRITICAL_MOISTURE": "मिट्टी गंभीर रूप से सूखी है! फसल को सूखने से बचाने के लिए तुरंत सिंचाई की आवश्यकता है।",
        "HEAT_STRESS": "अत्यधिक गर्मी ({temp}°C) दर्ज की गई। पौधों की नमी बनाए रखने और फसल को ठंडा रखने के लिए हल्की सिंचाई की सलाह दी जाती है।",
        "WAIT_AND_WATCH": "मिट्टी और पानी का संतुलन सही है। स्थितियों की निगरानी की जा रही है।",
        "SENSOR_LOW_BATTERY": "चेतावनी: सेंसर की बैटरी कम है। डेटा गलत हो सकता है।"
    }
}

def get_message(key: str, lang: str = "en", **kwargs) -> str:
    """
    Retrieves and formats a localized message based on the decision key.
    
    Args:
        key: The reason_code generated by the RecommendationEngine.
        lang: Language code (default 'en').
        **kwargs: Variables like 'temp', 'rainfall_mm', or 'id' for string formatting.
    """
    # Normalize language code (e.g., "hi-IN" -> "hi")
    lang_code = lang[:2].lower()
    
    # Fallback to English if the requested language is not supported
    dictionary = TRANSLATIONS.get(lang_code, TRANSLATIONS["en"])
    
    # Get the message template; fallback to the key itself if not found
    message_template = dictionary.get(key, key)
    
    try:
        # Interpolate variables into the message (e.g., {temp} -> 38)
        return message_template.format(**kwargs)
    except KeyError as e:
        # If a required variable is missing in kwargs, return the raw template to avoid crash
        return message_template
    except Exception:
        return message_template